### ISSUE TITLE
NO POS COINS

### ISSUE THREAD

**Issue by Mustyphil** [davorcc/DavorCoin#5]
HI Davorcoin Team, 
Its over 17Days now that i have started staking and i am yet to receive any coins for staking. the staking expected time to earn reward has been 2 days since a week ago. why this? is there a minimum amount of coins to stake? Resolve the issue please.

Best Regards.

**Comment by davorcc** [comment]
Hi Mustyphil,

The staking progress is based on probability. So that we could not guarantee that your staking wallet will get the rewarding coins at the estimated time. But do not worry, Davor.io is implementing the staking pool. By participating in the pool, you can get the rewarding coins 2 times per day and that is guaranteed. Please stay tune to our social update for the release day.

Best regards,
